### ISSUE TITLE
barrier status codes

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdams#6]
I do not believe the barrier status of every dam has been checked.

While dams seem more likely to be barriers than culverts, in absence of better data, the barrier status of dams should probably be defaulting to "potential barrier" as per modelled culverts.

**Comment by smnorris** [comment]
I think we can just tweak the barrier coding.

Remove `barrier_ind` and replace with `barrier_status` as per `bcfishpass.crossings`.

Update current data like this:

```
ogr2ogr -f GeoJSON \
  dams_new.geojson \
  -dialect SQLITE \
  -sql "SELECT
bcdams_id,
source_dataset,
source_id,
dam_name,
waterbody_name,
owner,
hydro_dam_ind,
case 
  when barrier_ind = 'N' then 'PASSABLE'
  when barrier_ind = 'Y' and hydro_dam_ind = 'Y' then 'BARRIER'
  else 'POTENTIAL'
end as barrier_status
from bcdams" \
bcdams.geojson
```

**Comment by smnorris** [comment]
@nickw-CWF @captainmarmot @NewGraphEnvironment, any other thoughts on this?

Changing default dam barrier status to `POTENTIAL` should not have much (any?) effect on the modelling and reporting.

I notice the issue when mapping. When making this request: https://features.hillcrestgeo.ca/bcfishpass/collections/bcfishpass.crossings/items.html?barrier_status=BARRIER I only expected PSCIS confirmed barriers... because dams are returned as well there many more features than I expected.

**Comment by nickw-CWF** [comment]
I'm open to changing the default barrier status for dams to 'POTENTIAL', but dams aren't like stream crossings where 30%+ of unassessed crossings are going to be passable. Unless there is a fish passage structure or the dam has been decommissioned, then a dam will be a barrier, and the number that have fish passage/are decommissioned will be quite low.

Wouldn't this query solve your issue: https://features.hillcrestgeo.ca/bcfishpass/collections/bcfishpass.crossings/items.html?barrier_status=BARRIER&crossing_feature_type!=DAM?

**Comment by smnorris** [comment]
Yes - while that query is not doing the filter (I will have to look into why, it looks fine to me), there is no issue working around this if defaulting to barrier is preferred. 

Agreed that most will be barriers, and far more than road crossings. For features coming from FISS and FWA though, I'm not as confident a dam will actually be present. It may be like falls from those sources - not reliable enough to confidently say there is a barrier present.

**Comment by CaptainMarmot** [comment]
I would agree that most dams will be barriers.  Perhaps a further filter to say that the dams from the vetted dams layer are barriers but the dams from FISS and FWA are potentials?

**Comment by nickw-CWF** [comment]
We just finished processing the CABD dam data for BC - this is essentially ```bcdams``` with additional data sources and full QA/QC. The dams layer has manually been deduplicated, georeferenced, and any non-existent structures removed.

The CABD dam layer could replace the base dams layer - I could have Katherine or Alex incorporate our manual updates to ```bcdams```in the CABD data.

**Comment by smnorris** [comment]
Great news.
Is there an API to extract features from CABD?

**Comment by nickw-CWF** [comment]
> Great news. Is there an API to extract features from CABD?

Yes, there is! The BC data is not loaded in just yet, we are just doing some final pre-release checks, but it should be up by the end of the week.

The relevant request would be: ``https://cabd-web.azurewebsites.net/cabd-api/features/dams?filter=province_territory_code:eq:bc``

In the meantime if you want to test it out/see the data structure, you can try it for Alberta: ``https://cabd-web.azurewebsites.net/cabd-api/features/dams?filter=province_territory_code:eq:ab``

**Comment by smnorris** [comment]
Excellent. I'll plan to archive this repository.

**Comment by smnorris** [comment]
It looks like `up_passage_type_code` would be the key attribute for bcfishpass purposes. AB has values `1`, `2`,`3`,`6` - can you provide a list of codes and descriptions?

**Comment by nickw-CWF** [comment]
The most relevant would actually be ``passability_status_code``:

| Code  | Value |
| ------------- | ------------- |
| 1  | Barrier  |
| 2  | Partial Barrier  |
| 3 | Passable |

Default value is ``1``/Barrier for dams. Because we need the passability status to be flexible across Canada (for all species, etc.), any dam with a known fish passage structure is assigned ``2``/Partial Barrier rather than ``3``/Passable. These structures will be passable for some species, but not for others.

``up_passage_type_code`` identifies the *type* of fish passage structure that exists.

**Comment by smnorris** [comment]
Perfect, thanks @nickw-CWF. 

Is there a preferred mechanism for requesting/submitting updates?
